// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtybEeNMIEP7kfHMVLc_fLLrecrUDzVtI',
    appId: '1:544067786065:web:88b9b7da52770255c3ef70',
    messagingSenderId: '544067786065',
    projectId: 'flutterproject-a11ae',
    authDomain: 'flutterproject-a11ae.firebaseapp.com',
    storageBucket: 'flutterproject-a11ae.appspot.com',
    measurementId: 'G-VM5W9SEPKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUeLUK8YxRTLLVN-WlSE9hzdLxmha7kB8',
    appId: '1:544067786065:android:69c767933d3d0112c3ef70',
    messagingSenderId: '544067786065',
    projectId: 'flutterproject-a11ae',
    storageBucket: 'flutterproject-a11ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnUOPvB8nwqWeRrZHqeqi9yjT-laZtjc',
    appId: '1:544067786065:ios:c0499c8df150d407c3ef70',
    messagingSenderId: '544067786065',
    projectId: 'flutterproject-a11ae',
    storageBucket: 'flutterproject-a11ae.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYnUOPvB8nwqWeRrZHqeqi9yjT-laZtjc',
    appId: '1:544067786065:ios:c0499c8df150d407c3ef70',
    messagingSenderId: '544067786065',
    projectId: 'flutterproject-a11ae',
    storageBucket: 'flutterproject-a11ae.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtybEeNMIEP7kfHMVLc_fLLrecrUDzVtI',
    appId: '1:544067786065:web:04e62cfc16aab4cec3ef70',
    messagingSenderId: '544067786065',
    projectId: 'flutterproject-a11ae',
    authDomain: 'flutterproject-a11ae.firebaseapp.com',
    storageBucket: 'flutterproject-a11ae.appspot.com',
    measurementId: 'G-P2XCZWGBMW',
  );
}
